### ISSUE TITLE
Does community really needs a separate package for such simple task?

### ISSUE THREAD

**Issue by devlato** [MoOx/multili#4]
Hello,

do you really think that community really needs a separate package for such simple task?

**Comment by MoOx** [comment]
Hi.
This such simple task is still around [50 lines](https://github.com/MoOx/multili/blob/master/src/index.js), covered by 6 tests https://github.com/MoOx/multili/blob/master/src/__tests__/index.js, and without any dependency.

A lot of package on npm are even smaller than this one. It's one of node/npm strengths.

So yes, I think it's a good thing. Feel free to not use it :)

**Comment by kof** [comment]
Totally with you on this @MoOx, though we got 2 good packages which can already do this. https://github.com/sindresorhus/strip-indent and https://www.npmjs.com/package/common-tags

**Comment by MoOx** [comment]
@kof can't remember why but I tried the sindre version and I think something was incorrect for my need. I think empty lines are handled differently.

**Comment by kof** [comment]
maybe worth a pr to fix or an option to add over there, also I use common-tags, they have multiple utils which are a bitt different.

**Comment by MoOx** [comment]
Some PR I did in the past to sindre were rejected, and I know this one won't be accepted as it's kind of not the same scope. And I am lazy :)

**Comment by kof** [comment]
puhh, thats bad ... I understand you and yet its bad for npm/community in general
